serverhost: 127.0.0.1
serverport: 8002
tunnel: cp
# http 转发规则，tag-标识；host-域名/ip；port-端口
# 例子：k3=10.1.3.198:8080
rules:
- tag: neo
  host: 127.0.0.1
  port: 8080
- tag: authentication
  host: 127.0.0.1
  port: 8081